### PR TITLE
medium: filter exist parameters

### PR DESCRIPTION
**Pull request by liangxin1300**
Apply this commit to avoid this completion situation:
1. primitive vip ocf:Heartbeat:IPaddr2 params ip=10.10.10.123 nic=eth1 nic=xxxx ip=xxxx
2. primitive vip ocf:Heartbeat:IPaddr2 meta is-managed=xxx is-managed=xxx

### CODE REVIEW

**Comment by liangxin1300** [comment]
Append commit: low: ui_configure: Improve do_group completer
1. There is no "params" in do_group configure
2. Complete all of rsc_meta_attributes after "meta" key word
3. filter already completed resource ids and meta nv pairs

**Comment by krig** [comment]
I think the complexity of the implementation could be reduced by using the `[item for arg in list if filter(arg)]` style, something like

```
[s+'=' for s in agent.params(completion=True) if s not in args]
```

**Comment by liangxin1300** [comment]
Oh, thank you. I will change that:)

**Comment by liangxin1300** [comment]
hi krig, I've changed the code, please review it
Thanks!

**Comment by liangxin1300** [comment]
Append commit: low: constants: adjust group/clone/ms options according to latest doc
According to 
http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html-single/Pacemaker_Explained/index.html#_group_properties
http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html-single/Pacemaker_Explained/index.html#_clone_properties
http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html-single/Pacemaker_Explained/index.html#_multi_state_properties

**Comment by liangxin1300** [comment]
Append commit: low: ui_configure: Improve do_clone completer
1 Complete specific meta_attributes after "meta" key word
2 filter already completed resource ids and meta nv pairs

**Comment by liangxin1300** [comment]
Append Commit: low: constants: adjust resource options according to latest doc
According to latest document, group/clone/ms inherited three options from primitive resources: priority, target-role, is-managed

**Pull request closed without merging**
