### PR TITLE
[crmsh-4.6] Dev: utils: Avoid hardcoding the ssh key type as RSA

### PR DESCRIPTION
**Pull request by liangxin1300**
backport #1600

### CODE REVIEW

**Comment by nicholasyang2022** [comment]
I think we should not add this new feature to 4.6.

**Comment by liangxin1300** [comment]
> I think we should not add this new feature to 4.6.

Do you think this is a feature or issue fix? this PR doesn't change the default key as the RSA
@zzhou1

**Comment by zzhou1** [comment]
> > I think we should not add this new feature to 4.6.
> 
> Do you think this is a feature or issue fix? this PR doesn't change the default key as the RSA @zzhou1

I think I agree with @nicholasyang2022 as a master branch feature to adapt to the latest Tumbleweed. I don't see the reasonable justification in 4.6 as a bug fix.

**Comment by liangxin1300** [comment]
Let's reopen this when this is needed

**Pull request closed without merging**
