### PR TITLE
Fix issue in to_ascii (bsc#1138115)

### PR DESCRIPTION
**Pull request by arbulu89**
When coming string has non utf-8 characters the
error is ignored

Fixes bsc#1138115

### CODE REVIEW

**Comment by krig** [comment]
Hey :) Please format the commit message according to the standard format in crmsh:

`high|medium|low: module: message (bsc#...)`

**Comment by diegoakechi** [comment]
@arbulu89 as mentioned by @krig, please, format the commit message and the PR title following the standard format. In general, it LGTM.

**Comment by diegoakechi** [comment]
@arbulu89 The structure of the commit message should be: `low: utils: issue in to_ascii (bsc#1138115)`

**Comment by arbulu89** [comment]
> @arbulu89 The structure of the commit message should be: `low: utils: issue in to_ascii (bsc#1138115)`

It's OK for me. I put `Fix` because I found several commits with this tag and It seemed more appropiated.

**Pull request merged**
