### PR TITLE
ui_cluster: restart cluster is added

### PR DESCRIPTION
**Pull request by aleksei-burlakov**

### CODE REVIEW

**Comment by ChrisKowalczyk** [comment]
Good change, Aleksei, we have been missing this feature for some time..!

**Comment by krig** [comment]
Looks good, thanks for updating the documentation as well :)

**Comment by gao-yan** [comment]
Good thinking. Not sure if it depends on how ExecStop is defined in the service file, it's not clear if it's really by default synchronous or asynchronous,  given that there are "systemctl --no-block/--wait" options.

Of course another solution is to invoke "systemctl restart corosync".

**Comment by aleksei-burlakov** [comment]
I checked that `crm cluster stop` really wait's until the cluster has stopped. Besides, if an exception was thrown, then crm won't try to start the cluster.

**Pull request merged**
