### PR TITLE
medium: bootstrap: use strict regrex for bindnetaddr/mcastaddr/adminIP

### PR DESCRIPTION
**Pull request by liangxin1300**
Commit sets for more robust bootstrap config:
1) medium: bootstrap: use strict regrex for bindnetaddr/mcastaddr/adminIP
2) low: bootstrap: color the input error message
3) low: bootstrap: valid bindnetaddr must one of the local networks
4) medium: bootstrap: csync2 update after all things done at local
       If don't do this, some files sync failed, when:
    step 1) a configured, running well cluster(two nodes for example);
    step 2) stop every node's service;
    step 3) on node A, run crm->cluster->init, reconfigure corosync;
    setp 4) after that, on node B, run crm->cluster->join;
    then bootstrap say "! csync2 run failed - some files may not be sync'd"
    and then, the cluster split as two one-node clusters,
    two nodes can't see each other!

    So, call csync2_update after all things done will solve this problem

5) medium: bootstrap: add valid_adminIP to valid adminIP
    The administration virtaul IP must:
    - have a valid ipv4 formation
    - belongs one of local networks

### CODE REVIEW

**Comment by krig** [comment]
Hmm, for the validation, I wonder if this is breaking IPv6 support - not sure if it was possible to configure IPv6 before. If not, maybe it should be. I need to look at that...

**Comment by liangxin1300** [comment]
for now, the regrex '([0-9]+\.){3}[0-9]+' does not support IPv6 either

**Comment by liangxin1300** [comment]
append another commit:
medium: enable add the second heartbeat for mcast
    features include:
    1) skip second configure when local networks < 2
    2) bindnetaddrs must be different and
       the gap between ports must larger than 1
    3) give different default value for second config

**Comment by krig** [comment]
Well, we don't want to make it impossible to use IPv6!

**Comment by liangxin1300** [comment]
Ok, I will figure it out and split this commit set.
Thanks!

**Pull request closed without merging**
