### PR TITLE
Dev: Parametrize the log dir

### PR DESCRIPTION
**Pull request by aleksei-burlakov**
By default all logs are stored in `/var/lib/heartbeat/trace_ra`
This patch adds a new resource attribute trace_dir to the `cib.file`
The `trace_dir` should come alongside the `trace_ra`,
whereas `trace_ra` signals that the resource is traced,
the `trace_dir` defines the path.

### CODE REVIEW

**Comment by jpbuecken** [comment]
Nice, as a user, this is what we needed (as you know, a cluster is used to mitigate downtimes, and if we need to enable tracing in production a full /var is not very good to avoid downtimes :-) ).

Question: Will trace_dir be available as cluster wide default option so we can add it to our default setup and only switch trace_ra per resource if needed?

e.g
```
rsc_defaults rsc-options: \
        resource-stickiness=100 \
        is-managed=true \
        trace_dir="/extra/trace/fs"
```

**Comment by aleksei-burlakov** [comment]
Oops, I forgot to put the reference to the draft PR https://github.com/ClusterLabs/crmsh/pull/935

@jpbuecken , exactly, the cib file will be changed like (assumung there is a `Dummy` resource `dummy1`)

```
     <resources>                                                                                                                                                                             
       <primitive id="dummy1" class="ocf" provider="pacemaker" type="Dummy">                                                                                                                 
         <operations>                                                                                                                                                                                                    
          <op name="monitor" interval="15" id="dummy1-monitor-15"/>
           <op name="start" interval="0" id="dummy1-start-0">
             <instance_attributes id="dummy1-start-0-instance_attributes">
                <nvpair name="trace_ra" value="1" id="dummy1-start-0-instance_attributes-trace_ra"/>
+               <nvpair name="trace_dir" value="/foo/bar" id="dummy1-start-0-instance_attributes-trace_dir"/>
              </instance_attributes>                                                           
           </op>                                                                              
         </operations>                                                                        
       </primitive>                                                                           
     </resources>
```

**Comment by gao-yan** [comment]
> Question: Will trace_dir be available as cluster wide default option so we can add it to our default setup and only switch trace_ra per resource if needed?

It's an op parameter, so it's likely to work with op_defaults like:
```
op_defaults trace_dir="/extra/trace/fs"
```

**Comment by aleksei-burlakov** [comment]
Hi @liangxin1300 , can you please approve my PR?

**Comment by liangxin1300** [comment]
> Hi @liangxin1300 , can you please approve my PR?

Sorry for late, I will take a look today

Thanks!

**Comment by liangxin1300** [comment]
Other part of codes looks good to me.
Nice work! @aleksei-burlakov 
After changing the doc part, I will merge and submit the code into 15SP4 in next week

**Review by liangxin1300 — APPROVED** [review]

**Pull request merged**
