### PR TITLE
Dev: ui_resource: resolve maintenance vs is-managed conflict

### PR DESCRIPTION
**Pull request by aleksei-burlakov**
The maintenance and is-managed are conflicting atributes. When setting
one of them, the user is proposed to remove another.

### CODE REVIEW

**Comment by aleksei-burlakov** [comment]
@krig, @liangxin1300, please review the PR.

**Comment by aleksei-burlakov** [comment]
> Please add a unit test that verifies the change :)

@krig , I have added a regression test.

**Comment by aleksei-burlakov** [comment]
@krig, could you please check it out?

**Comment by krig** [comment]
It would be good to include a link to the documentation or some kind of clarification in the info message, I think just the question like that is going to confuse people who aren’t clear about the difference between is-managed and maintenance mode.

**Comment by aleksei-burlakov** [comment]
> It would be good to include a link to the documentation or some kind of clarification in the info message, I think just the question like that is going to confuse people who aren’t clear about the difference between is-managed and maintenance mode.

https://github.com/ClusterLabs/pacemaker/blob/13b7e117dfba0603791d9d72dc0a4d3737a256ec/doc/Pacemaker_Explained/en-US/Ch-Resources.txt#L337

This exists only on the github now.

**Comment by aleksei-burlakov** [comment]
@krig, I have changed the output message and the help for crm maintenance and crm manage.

**Comment by krig** [comment]
Perfect, thank you!

**Pull request merged**
