### PR TITLE
Dev: behave: update test container to latest tumbleweed and use knet-1.29

### LINKED ISSUE #1572: systemd startup takes 30s in test container image built with latest opensuse tumbleweed
```
hanode1:/ # systemd-analyze critical-chain
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @30.277s
└─multi-user.target @30.277s
  └─systemd-logind.service @30.260s +16ms
    └─basic.target @30.259s
      └─dbus-broker.service @30.277s +5ms
        └─dbus.socket @30.259s
          └─sysinit.target @30.258s
            └─systemd-update-done.service @30.255s +2ms
              └─systemd-journal-catalog-update.service @30.251s +3ms
                └─systemd-tmpfiles-setup.service @30.243s +7ms
                  └─systemd-sysusers.service @30.065s +177ms
                    └─systemd-journald.socket @30.060s
                      └─-.mount @30.056s
                        └─-.slice @30.056s
```

See:

* https://github.com/ClusterLabs/crmsh/actions/runs/11090819942/job/30813642329?pr=1571
* c9a80d0af23b1669b48277dc9ce333b74ff3424a

### PR DESCRIPTION
**Pull request by nicholasyang2022**
* use knet-1.29 and rebuild the test container with latest tumbleweed
* replace privileged docker containers with unprivileged podman containers
    * latest systemd in tumbleweed does no longer like to run in a privileged container. Instead it need the container runtime to setup a environment according to CONTAINER_INTERFACE[^1].
* replace legacy iptables with iptables-nft
    * legacy iptables does not work in unprivileged containers
* stop using the default bridge container network
    * ha_netowork_first and ha_network_second are enough for functional tests
    * the default bridge network makes network interface names inside the containers unstable

close #1572.

[^1]: https://systemd.io/CONTAINER_INTERFACE/

### CODE REVIEW

**Comment by liangxin1300** [comment]
Please cleanup unused info while running run-functional-tests with -d option, and it'd better to add
> INFO: Cleanup container "xxx"...

This PR:
```
# ./test/run-functional-tests -d
hanode2
hanode1
INFO: Cleanup ha specific container network "ha_network_first"...
ha_network_first
INFO: Cleanup ha specific container network "ha_network_second"...
ha_network_second
```
Current code:
```
# ./test/run-functional-tests -d
INFO: Cleanup container "hanode1"...
INFO: Cleanup container "hanode2"...
INFO: Cleanup ha specific docker network "ha_network_first"...
INFO: Cleanup ha specific docker network "ha_network_second"...
```

**Comment by liangxin1300** [comment]
When I manually run `# ./test/run-functional-tests <test_num>`, it seems the process can't be killed by `Ctrl+C`? Which works in current master code

**Comment by nicholasyang2022** [comment]
> When I manually run `# ./test/run-functional-tests <test_num>`, it seems the process can't be killed by `Ctrl+C`? Which works in current master code

This seems to be related to the pseudo tty implementation provided by `podman exec -t`. The tty does not generate a SIGINT on `^C`.

Sending SIGINT to the `podman exec` prcoess (`kill -SIGINT <PID>`), or sending SIGINT to the process group of `run-functional-test` bash process (`kill -SIGINT -<PGID>`) will terminate the process.

**Comment by nicholasyang2022** [comment]
> Please cleanup unused info while running run-functional-tests with -d option, and it'd better to add
> 
> And the `ha_network_first` `ha_network_second` and these long commit string, should be cleaned up

Changed. Instead of redirect all the outputs to /dev/null, I redirects stdout only, so that we will know what happens when it fails.

**Comment by nicholasyang2022** [comment]
@liangxin1300 ping

**Review by liangxin1300 — APPROVED** [review]

**Comment by liangxin1300** [comment]
Thanks for the great work!

**Pull request merged**
