### PR TITLE
medium: ui_cluster: Stop corosync when stopping pacemaker (bsc#1066156)

### PR DESCRIPTION
**Pull request by krig**

### CODE REVIEW

**Comment by krig** [comment]
@gao-yan @liu4480 Is this what you meant? Start only pacemaker, but stop both.

**Comment by liu4480** [comment]
@krig  stoppting both could work, but what I mean is stop only by using "service corosync stop", pacemaker will also stop

**Comment by gao-yan** [comment]
On 2018/1/11 9:42, Kristoffer Grönlund wrote:
> @gao-yan <https://github.com/gao-yan> @liu4480 
> <https://github.com/liu4480> Is this what you meant? Start only 
> pacemaker, but stop both.
Or simply stop corosync ;)

**Comment by krig** [comment]
Hm, I see :) OK, will do that instead.

**Pull request merged**
