### PR TITLE
low: ui_cluster: when use -h/--help option, do not exit

### PR DESCRIPTION
**Pull request by liangxin1300**
just print help messages and return

### CODE REVIEW

**Comment by krig** [comment]
Can you explain why make this change?

**Comment by liangxin1300** [comment]
For staying with the shell,
for example,
1) crm->report -h, then program will print the help info and stay with the prompt string
2) crm->ra -h, after showing the help info, program not exit, just stay and wait for next input

BTW, the code "return False", which at "do_init" and "do_join" function, will make the whole program exit other than stay with the shell, 
it's a little bit strict.

**Comment by liangxin1300** [comment]
I just create another commit in this PR,
to handle the optparse error(e.g. crm->cluster->init -x), and stay at the shell

**Comment by krig** [comment]
Ah, right.. yes. Makes sense. Thank you. :)

**Pull request merged**
