### PR TITLE
Feature: add version control to resources and simple constraints

### PR DESCRIPTION
**Pull request by igor-tsiglyar**
This extension provides interface to configure versioned resources and simple location, colocation and order constraints.
Please, review and leave feedback.

### CODE REVIEW

**Comment by krig** [comment]
Where do versioned resources come from? I tried looking in the pacemaker source code but can't find any mention of them. How does it work?

**Comment by igor-tsiglyar** [comment]
It comes from my not yet accepted [pull request](https://github.com/ClusterLabs/pacemaker/pull/1001).
Sorry, maybe I've opened this request a little bit early.
Versioned resource starts only if version parameter you stated when configured resource (e.g. 

> crm configure primitive A ocf:pacemaker:Dummy params version=1.1.1

) matches with resource agent version parameter obtained by 
> /usr/lib/ocf/resource.d/pacemaker/Dummy version

When it comes to constraints, now you can specify versions and comparators. For example,
> crm configure colocation A-with-B inf: A::1.1.1 B::1.1.2:gt

only applies to resource A with version == 1.1.1 and resource B with version >= 1.1.2

**Comment by krig** [comment]
Aaah, I see! OK, I'll wait to merge this.

It looks like a potentially useful feature, although version comparisons quickly become extremely complex - at least that's my experience from rpm and various programming language package managers.

**Comment by igor-tsiglyar** [comment]
Right you are! That's why after discussing this with the Pacemaker maintainers we decided to use rules interface, and there's no need to add a new one. So, I'll close the request. Thanx!

**Comment by krig** [comment]
Thanks for the update :)

**Pull request closed without merging**
