### PR TITLE
low: ui_context: reset term when using "help command+ctrlC"

### PR DESCRIPTION
**Pull request by liangxin1300**
If dont do this, type "ctrl+C" when using "help command" will cause
  the term lost curses

### CODE REVIEW

**Comment by liangxin1300** [comment]
Oh, it seems this change blocked on regression test.
Krig, I think you can skip these failed commits and continue doing the release work for factory,
we've done most of work after all.

**Comment by krig** [comment]
No problem! I think if you rebase on master now, Travis should print the details for the failure.

**Comment by liangxin1300** [comment]
My next plan for crmsh: bugfix, bundle, add some scripts for hawk wizard(like redis/nginx/tomcat/pgsql) :)

**Comment by krig** [comment]
Sounds good! Having some new scripts would be great :)

**Comment by liangxin1300** [comment]
This commit also passed test:)

Thanks!

**Pull request merged**
