### PR TITLE
[crmsh-4.6] Dev: doc: implement help2adoc (#1374)

### PR DESCRIPTION
**Pull request by nicholasyang2022**
This pull request includes:

1. a tool `help2adoc` to convert the help text generated by python `argparse` module to asciidoc
2. a series of helper scripts, makefiles, containers to automatic the process to combine the asciidocs generated by `help2adoc` and `crm.8.adoc` to generated a complete document

Usage:

```shell
$ cd doc/toolchain
$ podman build -t local/crmsh-doc-builder .
$ cd ..
$ make clean
$ podman run --rm -ti -v ..:/opt/crmsh local/crmsh-doc-builder:latest
```

The final results is `doc/generated-sources/crm.8.adoc` and `doc/generated-sources/crm.8.html`

Part of #1374.

### CODE REVIEW

**Comment by nicholasyang2022** [comment]
`TestUtils.test_findln_by_timestamp` fails in `crmsh-4.6`. It is unrelated to this pull request.

**Comment by liangxin1300** [comment]
> `TestUtils.test_findln_by_timestamp` fails in `crmsh-4.6`. It is unrelated to this pull request.

Fixed in https://github.com/ClusterLabs/crmsh/pull/1379/commits/0d66d03bae00b1ce963c99039121661579671a11

**Comment by liangxin1300** [comment]
Great job!

Then the next stage will be auto-submit the web contents to crmsh.github.io, in a GH action I guess, right?
The process, please see 'Website update' section at https://github.com/ClusterLabs/crmsh/blob/master/doc/releasing-a-new-version.md

**Review by liangxin1300 — APPROVED** [review]
Great job!

**Pull request merged**
