### PR TITLE
medium: ui_cluster: disable/enable completion when bootstrap running/…

### PR DESCRIPTION
**Pull request by liangxin1300**
…leaving

When running crm->cluster->init(or other bootstrap function),
completion make no sense, it's better to disable it,
and enable it before these function return

### CODE REVIEW

**Comment by krig** [comment]
Hmm, why not enable completion for init etc.?

**Comment by liangxin1300** [comment]
when user use init to config the cluster, 
for example,
input Network address to bind to, or input y/n to confirm something,
completion still work when type "TAB", the cluster sub-commands will all pop after these prompt string,
it's strange.

So, it's simple and clear to disable completion "temporarily" when enter these sub-commands(init, join, geo-init, geo-join, etc.); and enable completion when these commands done

**Comment by krig** [comment]
Aha, I see! I need to check, but it sounds like completion was happening incorrectly for any yes/no prompts then, not just in bootstrap.

But actually the right fix should be to have relevant completion for those prompts, and not sub-commands.

**Comment by liangxin1300** [comment]
I re-implement this in #252

**Pull request closed without merging**
