### PR TITLE
dev: bundle: add bundle sub-command

### PR DESCRIPTION
**Pull request by liangxin1300**
Hi all:
This commit is about bundle sub-command, changes include:
1. both docker and rkt container types are supported(create/delete/edit/show)
2. all options and keywords about bundle are well completed(include container options/network/network-mapping/storage(-mapping)/primitive/meta)
3. options with help messages which from latest documents in clusterlabs

Todo list:
1. test scripts
2. inputs validation if needed
3. more test

Any help or suggestions are welcome!
Thanks!

Regards,
xin

### CODE REVIEW

**Comment by krig** [comment]
Hi Xin, 

Great work! Could you also add test cases for the parser, and update the documentation?

**Comment by liangxin1300** [comment]
Yes, I will handle it.

> update the documentation
Do you mean the file crm.8.doc?

**Comment by krig** [comment]
I mean `doc/crm.8.adoc`, this is the file which generates the documentation for the man page, the internal help and also the website.

**Comment by liangxin1300** [comment]
hi, krig, please help to review this https://github.com/krig/salt-module-crmsh/pulls
it's ok to start salt-crmsh in that way?:)

**Comment by krig** [comment]
Would you prefer me to write the documentation? I could do that, then we could merge soon :)

**Comment by liangxin1300** [comment]
Yeah, thank you, krig. Frankly speaking, I'm not very familiar with docker now:)

**Comment by krig** [comment]
No problem :)

**Pull request merged**
