### PR TITLE
Fix: cibconfig: Disable auto complete advised operation values when adding a rsc_template

### LINKED ISSUE #1438: There is an error when configuring primitive resource with rsc_template
Run
```
crm configure rsc_template dummy_template ocf:pacemaker:Dummy op monitor interval=12s
```

Then
```
crm configure primitive d1 @dummy_template params passwd=123
```

Got error
```
ERROR: None:None: got no meta-data, does this RA exist? 
```

### PR DESCRIPTION
**Pull request by liangxin1300**
Run
```
crm configure rsc_template dummy_template ocf:pacemaker:Dummy op monitor interval=12s
```

Then
```
crm configure primitive d1 @dummy_template params passwd=123
```

Got error
```
ERROR: None:None: got no meta-data, does this RA exist? 
```

Solution: When adding a rsc_template as a primitive resource, should disable auto complete advised operation values

Fix #1438

### CODE REVIEW

**Comment by nicholasyang2022** [comment]
The regression tests fails. Do you need to rebase this?

**Comment by nicholasyang2022** [comment]
This problem happens when executing the command instead of activating the completion. I think completion related code should not be called here. This patch does not fix the root cause.

**Comment by liangxin1300** [comment]
> This problem happens when executing the command instead of activating the completion. I think completion related code should not be called here. This patch does not fix the root cause.

No, it has no relation with completion here.
Maybe the var term `complete_advised` confuses?
That means to complete RA's advised operation values if user not specify them

**Comment by nicholasyang2022** [comment]
> Maybe the var term complete_advised confuses?

Yes, appearing together with "cli" and "parse", it is so confusing. Can you change to a clearer variable name?

**Comment by liangxin1300** [comment]
> > Maybe the var term complete_advised confuses?
> 
> Yes, appearing together with "cli" and "parse", it is so confusing. Can you change to a clearer variable name?

Already changed the name of `complete_advised`
Regarding "cli" and "parse", since they are largely used and beyond the scope of this PR, I suggest to open an issue to trace?

**Review by nicholasyang2022 — APPROVED** [review]

**Pull request merged**
