### PR TITLE
Give hints where the next input need an unique id

### PR DESCRIPTION
**Pull request by liangxin1300**
Hi:
When I input these commands:
```
configure primitive
configure group
configure ms
configure clone
```
I don't have an idea to input an id if I'm not familiar with cluster
maybe I will get Error message when I type "Enter" or
maybe I will delete the line and type "help" to find useful info between the long help message

I think give hints here will be nice and fluent :)

Regards,
Xin

### CODE REVIEW

**Comment by liangxin1300** [comment]
BTW, if this PR make sense, other place use "compl.null" should be replaced by "mini_help"

**Comment by krig** [comment]
I like the idea, the only issue is that when doing bash completion, the hint prints as part of the command. So then the user has to erase the hint in order to enter the ID.

**Comment by liangxin1300** [comment]
Thank you for remind me that
I will check the option.interactive :)

**Comment by liangxin1300** [comment]
hi @krig, what's happen about the travis-ci? 
I noticed that some recent comments you pushed not sucess in ci with the same reason

**Comment by krig** [comment]
Hi, yeah, there is a problem with the Travis setup. For some reason, the build system started picking up the wrong python version inside the ubuntu environment.. I need to change the Travis configuration to adapt to whatever changed there.

**Pull request closed without merging**
