### PR TITLE
Feature: add versioned operations support

### PR DESCRIPTION
**Pull request by igor-tsiglyar**
This PR is to support versioned operations recently introduced by [#1127](https://github.com/ClusterLabs/pacemaker/pull/1127).

The syntax is as follows:
```
configure primitive A ocf:pacemaker:Dummy \
  op start \
    op_params 2: rule #ra-version version:lt 2.0 fake=real \
    op_params 1: fake=fake \
    op_meta 2: rule #ra-version version:gte 1.0 timeout=40s \
    op_meta 1: timeout=20s
```
generates
```
<primitive id="A" class="ocf" provider="pacemaker" type="Dummy">
  <operations>
    <op name="start" interval="0" id="A-start-0">
      <instance_attributes score="2" id="A-start-0-instance_attributes">
        <rule score="INFINITY" id="A-start-0-instance_attributes-rule">
          <expression attribute="#ra-version" operation="lt" value="2.0" type="version" id="A-start-0-instance_attributes-rule-expression"/>
        </rule>
        <nvpair name="fake" value="real" id="A-start-0-instance_attributes-fake"/>
      </instance_attributes>
      <instance_attributes score="1" id="A-start-0-instance_attributes-0">
        <nvpair name="fake" value="fake" id="A-start-0-instance_attributes-0-fake"/>
      </instance_attributes>
      <meta_attributes score="2" id="A-start-0-meta_attributes">
        <rule score="INFINITY" id="A-start-0-meta_attributes-rule">
          <expression attribute="#ra-version" operation="gte" value="1.0" type="version" id="A-start-0-meta_attributes-rule-expression"/>
        </rule>
        <nvpair name="timeout" value="40s" id="A-start-0-meta_attributes-timeout"/>
      </meta_attributes>
      <meta_attributes score="1" id="A-start-0-meta_attributes-0">
        <nvpair name="timeout" value="20s" id="A-start-0-meta_attributes-0-timeout"/>
      </meta_attributes>
    </op>
  </operations>
</primitive>
```

I think it's a good thing to be compatible with the former syntax as input:
```
primitive db0 mysql \
  params config=/etc/mysql/db0.conf \
  op monitor interval=60s \
  op monitor interval=300s OCF_CHECK_LEVEL=10
```
But I also think we should represent this with _crm configure show_ using the new one:
```
primitive db0 mysql \
  params config=/etc/mysql/db0.conf \
  op monitor interval=60s \
  op monitor interval=300s \
  op_params OCF_CHECK_LEVEL=10
```
That's why I've changed some of the tests.

### CODE REVIEW

**Comment by krig** [comment]
Hi, and thank you for the patch! I'm thinking about it. I'm not sure about the `op_params` and `op_meta` keywords, though I understand the need for them. I don't have much better ideas off-hand...

**Comment by krig** [comment]
Looks good, thank you!

**Comment by igor-tsiglyar** [comment]
You are welcome! Will this get into crmsh release for SLES?

**Comment by krig** [comment]
I will make sure that the support is included in any SLES version which includes ClusterLabs/pacemaker#1127, though it may take some time since it did not make it in time for 1.1.17.

**Comment by igor-tsiglyar** [comment]
It's all right! Thank you!

**Pull request merged**
