### PR TITLE
find_files function can not find link files in hb_report

### PR DESCRIPTION
**Pull request by liangxin1300**
find_files function cannot find link files;
So corosync-blackbox would not run when corosync have fdata

### CODE REVIEW

**Comment by krig** [comment]
No, this is incorrect: We don't care about the symlink, we care about the actual fdata files:
`find_files /var/lib/corosync $from_time $to_time | grep -w fdata` will find the actual data files within the `$from_time - $to_time` range.

The data files are named `fdata-$timestamp`, so `grep -w fdata` will find them correctly.

**Comment by krig** [comment]
An example:

```console
$ find_files /var/lib/corosync $from_time $to_time | grep -w fdata
/var/lib/corosync/fdata-2017-03-16T17:23:21-1725
/var/lib/corosync/fdata-2017-03-16T17:23:32-1725
```

**Comment by liangxin1300** [comment]
But corosync-blackbox actually call qb-backbox, which just care about /var/lib/corosync/fdata
```
$ tail -3 /usr/bin/corosync-blackbox
corosync-cmapctl -s runtime.blackbox.dump_state str $(date +%s)
corosync-cmapctl -s runtime.blackbox.dump_flight_data str $(date +%s)
qb-blackbox "/var/lib/corosync/fdata"
```

By the way, 
`[ -f "$inpf" ]` will never true when find more than one fdata file

**Comment by krig** [comment]
Well, the idea is that we'd only want to run if there's relevant data: some fdata file for the selected date range.

But you are right about the second point: that test should probably just be `[ -n "$inpf" ]`.

**Pull request closed without merging**
